### ISSUE TITLE
walkthrough notebook: loading image sequence as greyscale raises NotImplementedError

### ISSUE THREAD

**Issue by jeromefung** [soft-matter/trackpy-examples#8]
A colleague and I tried running the example notebook walkthrough.ipynb.  However, 

```python
frames = pims.ImageSequence('../sample_data/bulk_water/*.png', as_grey=True)
```
results in a NotImplementedError: "I don't know how to convert an image of shaped (424, 640, 4) to greyscale. Write you own function and pass it using the process_func keyword argument."

The ImageSequence gets loaded correctly when I remove the as_grey kwarg.  When I do that, each individual frame is RGBA, and frames[0].shape returns (424, 640, 4).  (It looks like the actual image loading is being done by PIL via scikit-image.)  Inspecting the _as_grey() method of FramesStream in base_frames.py in PIMS, it is clear that the presence of the alpha channel is raising the exception.  Am I doing something wrong?

PIMS and TrackPy were freshly cloned from GitHub, and the unit tests for both pass (except for TrackPy tests related to HDF5 storage in TrackPy, since PyTables is not installed).  I'm opening this issue here since I encountered the problem with the example notebook, but please feel free to move it to PIMS if that is more appropriate.  Thanks in advance.

**Comment by nkeim** [comment]
Fix was merged.
